name: Build and deploy ASP.Net Core app to Azure Web App - assignmate-kv-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore KeyVault/KeyVault.slnx

      - name: Build
        run: dotnet build KeyVault/KeyVault.slnx --configuration Release --no-restore

      - name: Publish
        run: dotnet publish KeyVault/KeyVault.slnx -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BBF74C6A117B45F4ACC322A610C8DF01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_420E7C2A1E734B45A9D8A779F82CFCC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD8A22D838E04875A427AFD92827038C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assignmate-kv-demo'
          slot-name: 'Production'
          package: ./publish
